//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBenXeThanhPho_DevEpress.Blazor.Server.ORMDataModel
{

    public partial class Admin : XPObject
    {
        string fIdAdmin;
        [DevExpress.Xpo.DisplayName(@"Id Admin")]
        public string IdAdmin
        {
            get { return fIdAdmin; }
            set { SetPropertyValue<string>(nameof(IdAdmin), ref fIdAdmin, value); }
        }
        string fTenAdmin;
        [DevExpress.Xpo.DisplayName(@"Tên Admin")]
        public string TenAdmin
        {
            get { return fTenAdmin; }
            set { SetPropertyValue<string>(nameof(TenAdmin), ref fTenAdmin, value); }
        }
        string fTaiKhoan;
        [DevExpress.Xpo.DisplayName(@"Tài Khoản")]
        public string TaiKhoan
        {
            get { return fTaiKhoan; }
            set { SetPropertyValue<string>(nameof(TaiKhoan), ref fTaiKhoan, value); }
        }
        string fMatKhau;
        [DevExpress.Xpo.DisplayName(@"Mật Khẩu")]
        public string MatKhau
        {
            get { return fMatKhau; }
            set { SetPropertyValue<string>(nameof(MatKhau), ref fMatKhau, value); }
        }
        [Association(@"TheXeReferencesAdmin")]
        public XPCollection<TheXe> TheXes { get { return GetCollection<TheXe>(nameof(TheXes)); } }
    }

}
