//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBenXeThanhPho_DevEpress.Blazor.Server.ORMDataModel
{

    public partial class BangLichTrinh : XPObject
    {
        string fIdLichTrinh;
        [DevExpress.Xpo.DisplayName(@"Id Lịch Trình")]
        public string IdLichTrinh
        {
            get { return fIdLichTrinh; }
            set { SetPropertyValue<string>(nameof(IdLichTrinh), ref fIdLichTrinh, value); }
        }
        string fGioXuatPhat;
        [DevExpress.Xpo.DisplayName(@"Giờ Xuất Phát")]
        public string GioXuatPhat
        {
            get { return fGioXuatPhat; }
            set { SetPropertyValue<string>(nameof(GioXuatPhat), ref fGioXuatPhat, value); }
        }
        string fDiemDen;
        [DevExpress.Xpo.DisplayName(@"Điểm Đến")]
        public string DiemDen
        {
            get { return fDiemDen; }
            set { SetPropertyValue<string>(nameof(DiemDen), ref fDiemDen, value); }
        }
        long fGiaVe;
        [DevExpress.Xpo.DisplayName(@"Giá Vé")]
        public long GiaVe
        {
            get { return fGiaVe; }
            set { SetPropertyValue<long>(nameof(GiaVe), ref fGiaVe, value); }
        }
        TaiXe fIdTaiXe;
        [Association(@"BangLichTrinhReferencesTaiXe")]
        [DevExpress.Xpo.DisplayName(@"Id Tài Xế")]
        public TaiXe IdTaiXe
        {
            get { return fIdTaiXe; }
            set { SetPropertyValue<TaiXe>(nameof(IdTaiXe), ref fIdTaiXe, value); }
        }
        XeCoDinh fIdXe;
        [Association(@"BangLichTrinhReferencesXeCoDinh")]
        [DevExpress.Xpo.DisplayName(@"Id Xe")]
        public XeCoDinh IdXe
        {
            get { return fIdXe; }
            set { SetPropertyValue<XeCoDinh>(nameof(IdXe), ref fIdXe, value); }
        }
    }

}
