//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBenXeThanhPho_DevEpress.Blazor.Server.ORMDataModel
{

    public partial class BangBaoCao : XPObject
    {
        string fIdBaoCao;
        [DevExpress.Xpo.DisplayName(@"Id Báo Cáo")]
        public string IdBaoCao
        {
            get { return fIdBaoCao; }
            set { SetPropertyValue<string>(nameof(IdBaoCao), ref fIdBaoCao, value); }
        }
        string fDoanhThu;
        [DevExpress.Xpo.DisplayName(@"Doanh Thu")]
        public string DoanhThu
        {
            get { return fDoanhThu; }
            set { SetPropertyValue<string>(nameof(DoanhThu), ref fDoanhThu, value); }
        }
        string fGhiChu;
        [DevExpress.Xpo.DisplayName(@"Ghi Chú")]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        NhanVienSoatVe fIdNhanVien;
        [Association(@"BangBaoCaoReferencesNhanVienSoatVe")]
        [DevExpress.Xpo.DisplayName(@"Id Nhân Viên")]
        public NhanVienSoatVe IdNhanVien
        {
            get { return fIdNhanVien; }
            set { SetPropertyValue<NhanVienSoatVe>(nameof(IdNhanVien), ref fIdNhanVien, value); }
        }
    }

}
