//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBenXeThanhPho_DevEpress.Blazor.Server.ORMDataModel
{

    public partial class LichSuRaVao : XPObject
    {
        string fIdLichSu;
        [DevExpress.Xpo.DisplayName(@"Id Lịch Sử")]
        public string IdLichSu
        {
            get { return fIdLichSu; }
            set { SetPropertyValue<string>(nameof(IdLichSu), ref fIdLichSu, value); }
        }
        string fThoiGianVao;
        [DevExpress.Xpo.DisplayName(@"Thời Gian Vào")]
        public string ThoiGianVao
        {
            get { return fThoiGianVao; }
            set { SetPropertyValue<string>(nameof(ThoiGianVao), ref fThoiGianVao, value); }
        }
        string fThoiGianRa;
        [DevExpress.Xpo.DisplayName(@"Thời Gian Ra")]
        public string ThoiGianRa
        {
            get { return fThoiGianRa; }
            set { SetPropertyValue<string>(nameof(ThoiGianRa), ref fThoiGianRa, value); }
        }
        string fBienSo;
        [DevExpress.Xpo.DisplayName(@"Biển Số")]
        public string BienSo
        {
            get { return fBienSo; }
            set { SetPropertyValue<string>(nameof(BienSo), ref fBienSo, value); }
        }
        string fLoaiXe;
        [DevExpress.Xpo.DisplayName(@"Loại Xe")]
        public string LoaiXe
        {
            get { return fLoaiXe; }
            set { SetPropertyValue<string>(nameof(LoaiXe), ref fLoaiXe, value); }
        }
        long fGiaTien;
        [DevExpress.Xpo.DisplayName(@"Giá Tiền")]
        public long GiaTien
        {
            get { return fGiaTien; }
            set { SetPropertyValue<long>(nameof(GiaTien), ref fGiaTien, value); }
        }
        XeCoDinh fIdXe;
        [Association(@"LichSuRaVaoReferencesXeCoDinh")]
        [DevExpress.Xpo.DisplayName(@"Id Xe")]
        public XeCoDinh IdXe
        {
            get { return fIdXe; }
            set { SetPropertyValue<XeCoDinh>(nameof(IdXe), ref fIdXe, value); }
        }
        NhanVienSoatVe fIdNhanVien;
        [Association(@"LichSuRaVaoReferencesNhanVienSoatVe")]
        [DevExpress.Xpo.DisplayName(@"Id Nhân Viên")]
        public NhanVienSoatVe IdNhanVien
        {
            get { return fIdNhanVien; }
            set { SetPropertyValue<NhanVienSoatVe>(nameof(IdNhanVien), ref fIdNhanVien, value); }
        }
    }

}
