//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBenXeThanhPho_DevEpress.Blazor.Server.ORMDataModel
{

    public partial class NhaXe : XPObject
    {
        string fIdNhaXe;
        [DevExpress.Xpo.DisplayName(@"Id Nhà Xe")]
        public string IdNhaXe
        {
            get { return fIdNhaXe; }
            set { SetPropertyValue<string>(nameof(IdNhaXe), ref fIdNhaXe, value); }
        }
        string fTenNhaXe;
        [DevExpress.Xpo.DisplayName(@"Tên Nhà Xe")]
        public string TenNhaXe
        {
            get { return fTenNhaXe; }
            set { SetPropertyValue<string>(nameof(TenNhaXe), ref fTenNhaXe, value); }
        }
        string fTenChuXe;
        [DevExpress.Xpo.DisplayName(@"Tên Chủ Nhà Xe")]
        public string TenChuXe
        {
            get { return fTenChuXe; }
            set { SetPropertyValue<string>(nameof(TenChuXe), ref fTenChuXe, value); }
        }
        string fTaiKhoan;
        [DevExpress.Xpo.DisplayName(@"Tài Khoản")]
        public string TaiKhoan
        {
            get { return fTaiKhoan; }
            set { SetPropertyValue<string>(nameof(TaiKhoan), ref fTaiKhoan, value); }
        }
        string fMatKhau;
        [DevExpress.Xpo.DisplayName(@"Mật Khẩu")]
        public string MatKhau
        {
            get { return fMatKhau; }
            set { SetPropertyValue<string>(nameof(MatKhau), ref fMatKhau, value); }
        }
        string fSoDT;
        [DevExpress.Xpo.DisplayName(@"Số Điện Thoại")]
        public string SoDT
        {
            get { return fSoDT; }
            set { SetPropertyValue<string>(nameof(SoDT), ref fSoDT, value); }
        }
        string fSoCCCD;
        [DevExpress.Xpo.DisplayName(@"Số Căn Cước Công Dân")]
        public string SoCCCD
        {
            get { return fSoCCCD; }
            set { SetPropertyValue<string>(nameof(SoCCCD), ref fSoCCCD, value); }
        }
        string fDiaChi;
        [DevExpress.Xpo.DisplayName(@"Địa Chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        short fSoLuongXe;
        [DevExpress.Xpo.DisplayName(@"Số Lượng Xe")]
        public short SoLuongXe
        {
            get { return fSoLuongXe; }
            set { SetPropertyValue<short>(nameof(SoLuongXe), ref fSoLuongXe, value); }
        }
        string fSoDTDatXe;
        [DevExpress.Xpo.DisplayName(@"Số Điện Thoại Đặt Xe")]
        public string SoDTDatXe
        {
            get { return fSoDTDatXe; }
            set { SetPropertyValue<string>(nameof(SoDTDatXe), ref fSoDTDatXe, value); }
        }
        [Association(@"YeuCauReferencesNhaXe"), Aggregated]
        public XPCollection<YeuCau> YeuCaus { get { return GetCollection<YeuCau>(nameof(YeuCaus)); } }
        [Association(@"XeCoDinhReferencesNhaXe"), Aggregated]
        public XPCollection<XeCoDinh> XeCoDinhs { get { return GetCollection<XeCoDinh>(nameof(XeCoDinhs)); } }
        [Association(@"TaiXeReferencesNhaXe"), Aggregated]
        public XPCollection<TaiXe> TaiXes { get { return GetCollection<TaiXe>(nameof(TaiXes)); } }
    }

}
