//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBenXeThanhPho_DevEpress.Blazor.Server.ORMDataModel
{

    public partial class TaiXe : XPObject
    {
        string fIdTaiXe;
        public string IdTaiXe
        {
            get { return fIdTaiXe; }
            set { SetPropertyValue<string>(nameof(IdTaiXe), ref fIdTaiXe, value); }
        }
        string fTenTaiXe;
        public string TenTaiXe
        {
            get { return fTenTaiXe; }
            set { SetPropertyValue<string>(nameof(TenTaiXe), ref fTenTaiXe, value); }
        }
        string fTaiKhoan;
        public string TaiKhoan
        {
            get { return fTaiKhoan; }
            set { SetPropertyValue<string>(nameof(TaiKhoan), ref fTaiKhoan, value); }
        }
        string fMatKhau;
        public string MatKhau
        {
            get { return fMatKhau; }
            set { SetPropertyValue<string>(nameof(MatKhau), ref fMatKhau, value); }
        }
        string fSoDT;
        public string SoDT
        {
            get { return fSoDT; }
            set { SetPropertyValue<string>(nameof(SoDT), ref fSoDT, value); }
        }
        string fDiaChi;
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fSoCCCD;
        public string SoCCCD
        {
            get { return fSoCCCD; }
            set { SetPropertyValue<string>(nameof(SoCCCD), ref fSoCCCD, value); }
        }
        string fGiayPhepLaiXe;
        public string GiayPhepLaiXe
        {
            get { return fGiayPhepLaiXe; }
            set { SetPropertyValue<string>(nameof(GiayPhepLaiXe), ref fGiayPhepLaiXe, value); }
        }
        string fNgayKiHopDong;
        public string NgayKiHopDong
        {
            get { return fNgayKiHopDong; }
            set { SetPropertyValue<string>(nameof(NgayKiHopDong), ref fNgayKiHopDong, value); }
        }
        string fThoiHanHopDong;
        public string ThoiHanHopDong
        {
            get { return fThoiHanHopDong; }
            set { SetPropertyValue<string>(nameof(ThoiHanHopDong), ref fThoiHanHopDong, value); }
        }
        NhaXe fIdNhaXe;
        [Association(@"TaiXeReferencesNhaXe")]
        public NhaXe IdNhaXe
        {
            get { return fIdNhaXe; }
            set { SetPropertyValue<NhaXe>(nameof(IdNhaXe), ref fIdNhaXe, value); }
        }
        [Association(@"BangLichTrinhReferencesTaiXe"), Aggregated]
        public XPCollection<BangLichTrinh> BangLichTrinhs { get { return GetCollection<BangLichTrinh>(nameof(BangLichTrinhs)); } }
    }

}
