//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBenXeThanhPho_DevEpress.Blazor.Server.ORMDataModel
{

    public partial class XeCoDinh : XPObject
    {
        string fIdXe;
        public string IdXe
        {
            get { return fIdXe; }
            set { SetPropertyValue<string>(nameof(IdXe), ref fIdXe, value); }
        }
        string fLoaiXe;
        public string LoaiXe
        {
            get { return fLoaiXe; }
            set { SetPropertyValue<string>(nameof(LoaiXe), ref fLoaiXe, value); }
        }
        string fBienSo;
        public string BienSo
        {
            get { return fBienSo; }
            set { SetPropertyValue<string>(nameof(BienSo), ref fBienSo, value); }
        }
        string fSoChoNgoi;
        public string SoChoNgoi
        {
            get { return fSoChoNgoi; }
            set { SetPropertyValue<string>(nameof(SoChoNgoi), ref fSoChoNgoi, value); }
        }
        string fNgayCapThe;
        public string NgayCapThe
        {
            get { return fNgayCapThe; }
            set { SetPropertyValue<string>(nameof(NgayCapThe), ref fNgayCapThe, value); }
        }
        string fSoLuotConLai;
        public string SoLuotConLai
        {
            get { return fSoLuotConLai; }
            set { SetPropertyValue<string>(nameof(SoLuotConLai), ref fSoLuotConLai, value); }
        }
        NhaXe fIdNhaXe;
        [Association(@"XeCoDinhReferencesNhaXe")]
        public NhaXe IdNhaXe
        {
            get { return fIdNhaXe; }
            set { SetPropertyValue<NhaXe>(nameof(IdNhaXe), ref fIdNhaXe, value); }
        }
        [Association(@"BangLichTrinhReferencesXeCoDinh"), Aggregated]
        public XPCollection<BangLichTrinh> BangLichTrinhs { get { return GetCollection<BangLichTrinh>(nameof(BangLichTrinhs)); } }
        [Association(@"LichSuRaVaoReferencesXeCoDinh"), Aggregated]
        public XPCollection<LichSuRaVao> LichSuRaVaos { get { return GetCollection<LichSuRaVao>(nameof(LichSuRaVaos)); } }
    }

}
