//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBenXeThanhPho_DevEpress.Blazor.Server.ORMDataModel
{

    public partial class YeuCau : XPObject
    {
        string fIdYeuCau;
        public string IdYeuCau
        {
            get { return fIdYeuCau; }
            set { SetPropertyValue<string>(nameof(IdYeuCau), ref fIdYeuCau, value); }
        }
        string fLoaiyeuCau;
        public string LoaiyeuCau
        {
            get { return fLoaiyeuCau; }
            set { SetPropertyValue<string>(nameof(LoaiyeuCau), ref fLoaiyeuCau, value); }
        }
        string fNoiDung;
        public string NoiDung
        {
            get { return fNoiDung; }
            set { SetPropertyValue<string>(nameof(NoiDung), ref fNoiDung, value); }
        }
        NhaXe fIdNhaXe;
        [Association(@"YeuCauReferencesNhaXe")]
        public NhaXe IdNhaXe
        {
            get { return fIdNhaXe; }
            set { SetPropertyValue<NhaXe>(nameof(IdNhaXe), ref fIdNhaXe, value); }
        }
    }

}
